import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/backend/Provider";
import Footer from "@/components/ui/Footer";
import Navbar from "@/components/ui/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Navbar/>
          {children}
       
          </Provider>

        </body>
    </html>
  );
}
